### ISSUE TITLE
Image: "Error Fetching Image" when scraping images from URL

### ISSUE THREAD

**Issue by tsekiguchi** [DWilliames/google-sheets-sync-figma#180]
**Describe the bug**
When importing into Figma, images are no longer being pulled in, and instead I'm receiving a "Error Fetching Image". These URL's were working yesterday, but now it is giving me an error message when pulling in. 

**To Reproduce**
Screen [Recording](https://drive.google.com/file/d/1NU37zPxnJIFQhsB49FqQ7ka-lpJXxlbK/view?usp=sharing)

**Expected behavior**
Import images like normal

**Additional context**

**Comment by Owenb888** [comment]
Yes can confirm I am now having the same issue!

**Comment by Owenb888** [comment]
@DWilliames

**Comment by tomimorigui** [comment]
Yes, I have the same problem, It started yesterday!

**Comment by lderossi** [comment]
The issue is caused by a proxy server image requests go through to deal with cors headers. 

The server is no longer available (figma-cors-anywhere.fly.dev). From the look of it, it's an instance of the cors-anywhere project (https://github.com/Rob--W/cors-anywhere) which is relatively simple to set up. 

@DWilliames could we get a setting in the plugin to define our own proxy if this one is not going to come back online (or open source the plugin so we can change it in there)?

**Comment by DWilliames** [comment]
Sorry everyone! 
I just looked into and found that somehow there were some weird unsupported characters in a URL that was used, and it broke the server entirely. 😢 
I've made some changes to make it more resilient and timeout after 10 seconds too, so a slow website won't cause the whole server to hang.

Try it now! As far as I can tell it looks to be working now. :)
