### ISSUE TITLE
When you copy and paste in figma a design, the plugin stop working in the new design.

### ISSUE THREAD

**Issue by hannah-ptf** [DWilliames/google-sheets-sync-figma#5]
**Describe the bug**
When you have one design with the layers named #keyword ready, and you run the plugin, it all work fine.
But when you copy and paste that design (the whole ), the new copies don't work.

I need the same design in 3 different sizes, so when I copy and paste the design and resize it to be different sizes, the copies stop working, and sometimes even the original design stop working, it all gets buggy.

**To Reproduce**
Here's a recording showing what I describe:
https://drive.google.com/file/d/1wgInwXNW1uI_7UxR4MoJuNMK1LddXZIu/view?usp=sharing

You create a design, add #keyword to the layers, you run the plugin, it works fine.
But now if you copy and paste that design and resize it, then run the plugin, the new design wont be filled with information when you run the plugin, it will stay as it is. 

**Expected behavior**
What I would love for the plugin to do is this:
Create one design, then I would copy and paste the same design and I would resize them in different sizes, then run the plugin and it will populates the all the designs with the same info, like this: http://prntscr.com/xe6c3s

But nope, it doesn't populate the copies, only the original first design populates.
The workaround I found is that you can't copy and paste the exact same design, I had to create every design from scratch manually and that way it does work. 

But I really need to copy and paste or else it will take me for ever to do all sizes and all events looks from scratch.

I really hope this can be fixed, it would save so much work to me and other designes who need to create up to 100 images for a single event, and I need to create each of these 100 images 3 different sizes. So it would be a life savior if this could be fixed someday. Thanks!

**Comment by DWilliames** [comment]
Hi @hannah-ptf thanks for reaching out. Sorry for the delay in getting back to you.
I really appreciate the video explanation; it helps a lot to understand your issue.

I know how to fix it for this scenario for you; but I wouldn't necessarily say it's a bug with the plugin.

### What's happening...
When the plugin fetching the Google Sheet, I can see in your recording it successfully fetched it as this: 
![image](https://user-images.githubusercontent.com/6570446/106347902-29675400-6316-11eb-8bf6-12b7fad5b327.png)

It will then use the information in the first row the first time it encountered the layers of `#NAME1`, `#HOUR`, `#DATE` etc.
However, the next time it encounters similar layers, it will attempt to use the next row in the Google Sheet, which in your scenario happens to have blank values.

When all the values are blank, it will simply leave the values as they were rather than overwriting them with nothing.

### How to fix it...
In your scenario you want each of those Frames to always use the first row in the Sheet.
In order to tell the plugin this, simply append `.1` to the end of the names of the Frames for your images.
For example the frames may now be called `Facebook size .1`, `Instagram size .1` etc.
This tells the plugin to always use the _first_ row in the spreadsheet, rather than incrementing the rows each time (which it does by default)

---

Let me know how you go.
In the interim I will close of this 'issue'. But if you find that suggestion doesn't work for you. Let me know, and I'll re-open this issue.

**Comment by hannah-ptf** [comment]
o...m...g
This all makes so much sense, thank you so much for taking the time to read and explain!!! I will test naming my layers like you mentioned so they all take info only from row1 and it doesnt look for next rows.

Thanks to your plugin I will be able to automate my work and create up to 400+ images a month with a figma  template and google sheet database. Thanks to this plugin I will save so much time, you have no idea how grateful I am I found it. So thank you so much!!
